<a href="https://colab.research.google.com/github/alperensayar/Track/blob/master/Untitled31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("country_vaccination_stats.csv")
df.head()

     country        date  daily_vaccinations   vaccines
0  Argentina  12/29/2020                 NaN  Sputnik V
1  Argentina  12/30/2020             15656.0  Sputnik V
2  Argentina  12/31/2020             15656.0  Sputnik V
3  Argentina    1/1/2021             11070.0  Sputnik V
4  Argentina    1/2/2021              8776.0  Sputnik V

In [ ]:
df.describe().T

                     count          mean  ...       75%        max
daily_vaccinations  1442.0  43349.586685  ...  27979.75  1126251.0

[1 rows x 8 columns]

In [ ]:
df.isnull().sum()

country                0
date                   0
daily_vaccinations    60
vaccines               0
dtype: int64

In [ ]:
"""
Code Implementation Task: Implement code to fill the missing data (impute) in daily_vaccinations column per country with the minimum daily vaccination number of relevant countries.  
Note: If a country does not have any valid vaccination number yet, fill it with “0” (zero). 
"""

'\nCode Implementation Task: Implement code to fill the missing data (impute) in daily_vaccinations column per country with the minimum daily vaccination number of relevant countries.  \nNote: If a country does not have any valid vaccination number yet, fill it with “0” (zero). \n'

In [ ]:
bool_series = pd.isnull(df["daily_vaccinations"])  

df[bool_series]

                   country  ...                               vaccines
0                Argentina  ...                              Sputnik V
28                 Austria  ...                        Pfizer/BioNTech
48                 Bahrain  ...             Pfizer/BioNTech, Sinopharm
77                 Belgium  ...                        Pfizer/BioNTech
103                 Brazil  ...                                Sinovac
113               Bulgaria  ...               Moderna, Pfizer/BioNTech
141                 Canada  ...               Moderna, Pfizer/BioNTech
184                  Chile  ...                        Pfizer/BioNTech
217                  China  ...                          CNBG, Sinovac
254             Costa Rica  ...                        Pfizer/BioNTech
280                Croatia  ...                        Pfizer/BioNTech
307                 Cyprus  ...                        Pfizer/BioNTech
324                Czechia  ...               Moderna, Pfizer/BioNTech
354                Denmark  ...               Moderna, Pfizer/BioNTech
384                Ecuador  ...                        Pfizer/BioNTech
386                England  ...    Oxford/AstraZeneca, Pfizer/BioNTech
422                Estonia  ...                        Pfizer/BioNTech
451                Finland  ...                        Pfizer/BioNTech
477                 France  ...                        Pfizer/BioNTech
499                Germany  ...               Moderna, Pfizer/BioNTech
528              Gibraltar  ...                        Pfizer/BioNTech
543                 Greece  ...                        Pfizer/BioNTech
572                Hungary  ...                        Pfizer/BioNTech
600                Iceland  ...               Moderna, Pfizer/BioNTech
627                  India  ...                    Covaxin, Covishield
638              Indonesia  ...                                Sinovac
652                Ireland  ...                        Pfizer/BioNTech
677            Isle of Man  ...                        Pfizer/BioNTech
682                 Israel  ...               Moderna, Pfizer/BioNTech
720                  Italy  ...                        Pfizer/BioNTech
750                 Kuwait  ...                        Pfizer/BioNTech
751                 Latvia  ...                        Pfizer/BioNTech
780              Lithuania  ...               Moderna, Pfizer/BioNTech
812             Luxembourg  ...                        Pfizer/BioNTech
838                  Malta  ...                        Pfizer/BioNTech
866                 Mexico  ...                        Pfizer/BioNTech
899            Netherlands  ...               Moderna, Pfizer/BioNTech
916       Northern Ireland  ...    Oxford/AstraZeneca, Pfizer/BioNTech
959                 Norway  ...                        Pfizer/BioNTech
988                   Oman  ...                        Pfizer/BioNTech
1016                Panama  ...                        Pfizer/BioNTech
1022                Poland  ...                        Pfizer/BioNTech
1050              Portugal  ...                        Pfizer/BioNTech
1079               Romania  ...                        Pfizer/BioNTech
1108                Russia  ...                              Sputnik V
1138          Saudi Arabia  ...                        Pfizer/BioNTech
1150              Scotland  ...    Oxford/AstraZeneca, Pfizer/BioNTech
1193                Serbia  ...  Pfizer/BioNTech, Sinopharm, Sputnik V
1211            Seychelles  ...                              Sinopharm
1226             Singapore  ...                        Pfizer/BioNTech
1238              Slovakia  ...                        Pfizer/BioNTech
1256              Slovenia  ...                        Pfizer/BioNTech
1278                 Spain  ...               Moderna, Pfizer/BioNTech
1300                Sweden  ...                        Pfizer/BioNTech
1322           Switzerland  ...                        Pfizer/BioNTech
1352                Turkey  ...                                Sinovac
1365  United Arab Emirates  ...             Pfizer/BioNTech, Sinopharm
1386        United Kingdom  ...    Oxford/AstraZeneca, Pfizer/BioNTech
1422         United States  ...               Moderna, Pfizer/BioNTech
1459                 Wales  ...    Oxford/AstraZeneca, Pfizer/BioNTech

[60 rows x 4 columns]

In [ ]:
def min_target(variable):
    temp = df[df[variable].notnull()]
    temp = temp[[variable, 'country']].groupby(['country'])[[variable]].min().reset_index()
    return temp

In [ ]:
min_target("daily_vaccinations")

                 country  daily_vaccinations
0              Argentina              6483.0
1                Austria              3368.0
2                Bahrain               943.0
3                Belgium                 1.0
4                 Brazil               112.0
5               Bulgaria               472.0
6                 Canada               866.0
7                  Chile                51.0
8                  China            187500.0
9             Costa Rica               240.0
10               Croatia               989.0
11                Cyprus               534.0
12               Czechia              1822.0
13               Denmark              1994.0
14               Ecuador               108.0
15               England             37625.0
16               Estonia               309.0
17               Finland               459.0
18                France              5000.0
19               Germany             19721.0
20             Gibraltar               520.0
21                Greece               549.0
22               Hungary              1339.0
23               Iceland                63.0
24                 India            112150.0
25             Indonesia             11823.0
26               Ireland               550.0
27           Isle of Man                90.0
28                Israel              6887.0
29                 Italy               926.0
30                Latvia               338.0
31             Lithuania               311.0
32            Luxembourg                62.0
33                 Malta               259.0
34                Mexico              1300.0
35           Netherlands              4000.0
36      Northern Ireland              1563.0
37                Norway               224.0
38                  Oman               817.0
39                Panama                 6.0
40                Poland              4300.0
41              Portugal              2791.0
42               Romania               712.0
43                Russia              3357.0
44          Saudi Arabia             14153.0
45              Scotland              3047.0
46                Serbia              1150.0
47            Seychelles               500.0
48             Singapore              2800.0
49              Slovakia               425.0
50              Slovenia              1270.0
51                 Spain             41496.0
52                Sweden              3859.0
53           Switzerland              3000.0
54                Turkey             67192.0
55  United Arab Emirates             30698.0
56        United Kingdom             46423.0
57         United States             57909.0
58                 Wales              1763.0

In [ ]:
a=df[bool_series].index

In [ ]:
for i in range(len(a)):
  if (df.loc[a[i]]["country"] in temp.values):
    df["daily_vaccinations"].fillna(temp[temp["country"]==df.loc[a[0]]["country"]]["daily_vaccinations"],inplace=True)
    
  else:
    df["daily_vaccinations"].fillna(0,inplace=True)

In [ ]:
df.isnull().sum()

country               0
date                  0
daily_vaccinations    0
vaccines              0
dtype: int64